### PR TITLE
Improve Dockerfile

### PR DESCRIPTION
**Pull request by SuperSandro2000**
This saves just over 200MB uncompressed and follow some best practices. 
```
docker images | grep felicette
felicette                                   latest              854f7da1165e        6 minutes ago       1.29GB
milhouse1337/felicette                      latest              be1fd7e006be        5 days ago          1.5GB
```

### CODE REVIEW

**Comment by plant99** [comment]
@milhouse1337 can review this better. Else I'll test and merge this over the weekend.

**Comment by milhouse1337** [comment]
@SuperSandro2000 Thank you for this, it looks great! 👍

You can even remove the comments, it was not intended to be pushed. 😅

@plant99 I will rebuild the image on Docker Hub, based on this update.

**Comment by milhouse1337** [comment]
@plant99 the Docker image has been updated.
https://hub.docker.com/r/milhouse1337/felicette/tags

The size before: 572.88 MB (compressed)
After: 454.23 MB (compressed)

**Comment by SuperSandro2000** [comment]
@milhouse1337 comments got removed. I was not sure what to do with them.

I did some basic testing and one City generated a somewhat blurry image but the other was just black. This also happened with you old image so it is probably not the fault of my changes.

**Comment by plant99** [comment]
@SuperSandro2000 could you please test it with `-l Amsterdam` ? 

I agree with the blurry and black image for some locations. 

Thanks for the review @milhouse1337

**Comment by SuperSandro2000** [comment]
Amsterdam does also not work.

**Comment by plant99** [comment]
Oh, weird. Let me look into it when I get back on a keyboard.

**Comment by SuperSandro2000** [comment]
bump

**Comment by SuperSandro2000** [comment]
bump

**Pull request closed without merging**
